### ISSUE TITLE
Suggestion about PHP 5 compatibility

### ISSUE THREAD

**Issue by llaville** [nikolaposa/monolog-factory#2]
Hello

Thanks for this great packages, that is very interresting. I've just one regret, that there is no version compatible with PHP 5. 

Perharps a version 1.x compatible PHP5, and get version 2.x compatible PHP 7.

What do you think about this ?

**Comment by nikolaposa** [comment]
Hey, I'm glad you like this library.

But as for PHP 5 support, I've used many PHP 7 features in both code and tests, so making them compatible with older PHP versions would be wasted effort . Besides, I believe that one of the ways to stimulate/make people use latest PHP versions is just by libraries specifying them in system requirements.

**Comment by llaville** [comment]
I'll have a deeper look tomorrow, but as at my office we still use PHP 5.6, I'd like to use your library.

I've myself created a solution, but it seems too complex to be understood by many of developpers in my current entreprise.

So, what is I will propose: I've able to create a PHP5 version and keep maintained until PHP 5 disappear completly. Are you agree ?

**Comment by nikolaposa** [comment]
Feel free to fork my library and adapt it work on PHP 5.6. That way someone will have a reference to my version that is PHP7-only. Also, I would appreciate if you don't publish it on Packagist for the private use-case you're having in your company, but rather tell the Composer to install it directly from GitHub repo.

**Comment by llaville** [comment]
Will do it (fork) in next days. And of course reference you ! 
In my compagny we will use my PHP 5 version until we switch to PHP 7, and then use your version !

Thanks for quick feedback : I've appreciated a lot !

**Comment by llaville** [comment]
The PHP 5 version will be a private copy available only on my compagny (with a credit note to your package and link of course).
When we will switch to PHP 7, one day, we will use your package ! I will close this question report now

**Comment by nikolaposa** [comment]
That's great, thank you.
