### ISSUE TITLE
Cannot define configuration for GroupHandler

### ISSUE THREAD

**Issue by alexpts** [nikolaposa/monolog-factory#4]
How can I describe config for GroupHandler?

**Comment by alexpts** [comment]
I prepared PR for resolve this case

**Comment by nikolaposa** [comment]
@alexpts Yeah, you're right, I think it's not possible to setup GroupHandler via configuration at the moment. Thanks for raising this one, I'll study this and your PR as well later this week.

**Comment by nikolaposa** [comment]
@alexpts Cascader 1.2 featuring support for objects collection arguments has been released today, so I've just it as a minimal version requirement in `composer.json`. I'm gonna tag new release soon. Thanks for reporting this one.
