### ISSUE TITLE
Update for monolog 2

### ISSUE THREAD

**Issue by thomasvargiu** [nikolaposa/monolog-factory#5]
Can you update the library to use monolog 2?

**Comment by nikolaposa** [comment]
Good idea, thanks for reminder. Hope to start working on it soon.

**Comment by nikolaposa** [comment]
Version 3.0.0 that is Monolog 2.0-compatible can now be pulled `3.0.0@dev`. There are many BC breaks, changes are described in CHANGELOG. I'll probably publish a new release later today.
