### ISSUE TITLE
Question: How add a processor for handler

### ISSUE THREAD

**Issue by alexpts** [nikolaposa/monolog-factory#6]
Monolog handler can push custom processor for a handler. Can I define processor for a handler (non all handlers) via this lib.

Example:
```
'monolog' => [
			'config' => [
                                  'processors' => [...], // global processors for all handlers
				'handlers' => [
					'kibana' => [ ... ],
					'stdout' => [
						'name' => StreamHandler::class,
						'options' => [
							'stream' => 'php://stdout',
						],
                                                  'processors' => [...], // I want add processors for current handler
					],
````

**Comment by nikolaposa** [comment]
Try putting `'processors'` into `'options'` array. The same is supported for `formatter`.

**Comment by alexpts** [comment]
Thanks!
It is work

**Comment by nikolaposa** [comment]
Feel free to open a PR with updated README and/or [examples](https://github.com/nikolaposa/monolog-factory/tree/master/examples).
