### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by acelaya** [nikolaposa/monolog-factory#7]
Hey!

Do you plan to support PHP 8 on this library? I can try to contribute the change if so.

**Comment by nikolaposa** [comment]
I do plan to add PHP 8 support to all my libraries in the foreseeable future, and contributions are welcome!

**Comment by acelaya** [comment]
In preparation for this, I have created a first PR replacing travis with Github Actions: https://github.com/nikolaposa/monolog-factory/pull/8

**Comment by acelaya** [comment]
I already have all the required changes ready to support PHP 8. I'll create the PR once a new version of cascader has been published.

**Comment by nikolaposa** [comment]
I've updated [branch alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias), so you should already be able to pull `cascader: 1.3.0`.

**Comment by acelaya** [comment]
![image](https://user-images.githubusercontent.com/2719332/101992655-4cca3700-3cb5-11eb-960f-b5c2d821c745.png)

Looks like it doesn't consider it stable enough.

**Comment by nikolaposa** [comment]
Oh yeah, minimum stability. I'll create a new release today or tomorrow.

**Comment by acelaya** [comment]
Perfect

**Comment by nikolaposa** [comment]
https://github.com/nikolaposa/cascader/releases/tag/1.3.0 🎉

**Comment by acelaya** [comment]
Very nice 🙂 

I have pushed again, as I realized `beberlei/assert` requires `intl` on its latest version, which is the one supporting PHP 8, so I had to add it to the actions.

Now the build is green.

**Comment by nikolaposa** [comment]
> I realized beberlei/assert requires intl on its latest version

Are you sure? 🤔  Latest stable?

**Comment by nikolaposa** [comment]
Scratch that, I haven't seen this one:

<img width="666" alt="Screenshot 2020-12-13 at 10 31 51" src="https://user-images.githubusercontent.com/6012807/102008124-85f2bd80-3d2e-11eb-8273-ea3a32d1fbf7.png">

**Comment by acelaya** [comment]
I have actually realized that `intl` is loaded by default 🤦🏼 https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-ubuntu-20.04

I'll revert that change.
